import { AnalysisResult } from "../schemas/analysis.schema";

export function formatADRComment(result: AnalysisResult, prUrl: string, adrFileUrl?: string): string {
  const risks = result.risks.length
    ? result.risks.map((r) => `- ⚠️ ${r}`).join("\n")
    : "- None identified";

  const decisions = result.decisions.length
    ? result.decisions.map((d) => `- ✅ ${d}`).join("\n")
    : "- None extracted";

  const adrLink = adrFileUrl
    ? `\n📄 [View saved ADR](${adrFileUrl})`
    : "";

  return `
## 🤖 DevDox — Architecture Decision Record

> Auto-generated from commits, PR description, and linked discussions.

---

### 📋 Summary
${result.summary}

---

### 🧠 Key Decisions
${decisions}

---

### 🚨 Risks
${risks}

---

### 📄 Full ADR

${result.suggestedADR}

---

<details>
<summary>ℹ️ About DevDox</summary>

This ADR was auto-generated by [DevDox](https://devdox-nu.vercel.app).
It reads your commits, PR description, and linked tickets to explain the *why* behind every change.

**Commands:** Comment \`@devdox regenerate\` to re-analyze · \`@devdox help\` for all commands

</details>

> 🔎 [View PR](${prUrl}) · Powered by DevDox${adrLink}
`.trim();
}