// src/bot/formatter.ts
import { AnalysisResult } from "../schemas/analysis.schema";

export function formatADRComment(result: AnalysisResult, prUrl: string): string {
  const risks = result.risks.length
    ? result.risks.map((r) => `- ⚠️ ${r}`).join("\n")
    : "- None identified";

  const decisions = result.decisions.length
    ? result.decisions.map((d) => `- ✅ ${d}`).join("\n")
    : "- None extracted";

  return `
## 🤖 DevDox — Architecture Decision Record

> Auto-generated from commits, PR description, and linked discussions.

---

### 📋 Summary
${result.summary}

---

### 🧠 Key Decisions
${decisions}

---

### 🚨 Risks
${risks}

---

### 📄 Full ADR

${result.suggestedADR}

---

<details>
<summary>ℹ️ About DevDox</summary>

This ADR was auto-generated by [DevDox](https://devdox.dev).  
It reads your commits, PR description, and linked tickets to explain the *why* behind every change.

</details>

> 📎 [View PR](${prUrl}) · Powered by DevDox
`.trim();
}