import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";
import { analyzePR } from "../services/analyzePR";
import { formatADRComment } from "./formatter";
import { AnalysisResult } from "../schemas/analysis.schema";
import { getCache, setCache } from "../lib/cache";

const SKIP_PATTERNS = [/\bwip\b/i, /\bdraft\b/i, /\btypo\b/i, /^test:/i, /^chore:/i, /^style:/i];

async function getInstallationAuth(installationId: number) {
  const rawKey = process.env.PRIVATE_KEY!
    .replace(/\\n/g, "\n")
    .replace(/^"/, "")
    .replace(/"$/, "")
    .trim();

  const auth = createAppAuth({
    appId: Number(process.env.APP_ID!),
    privateKey: rawKey,
    installationId,
  });

  const { token } = await auth({ type: "installation" });
  return { octokit: new Octokit({ auth: token }), token };
}

async function ensureDocsFolder(octokit: Octokit, owner: string, repo: string) {
  try {
    await octokit.repos.getContent({ owner, repo, path: "docs/decisions" });
  } catch {
    // Folder doesn't exist — create it with a README
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: "docs/decisions/README.md",
      message: "docs: initialize ADR folder via DevDox [skip ci]",
      content: Buffer.from(
        "# Architecture Decision Records\n\nAuto-generated by [DevDox](https://devdox-nu.vercel.app).\n\nEach file documents the *why* behind a pull request.\n"
      ).toString("base64"),
    });
    console.log(`[DevDox] Created docs/decisions/ folder in ${owner}/${repo}`);
  }
}

async function saveADRToRepo(
  octokit: Octokit,
  owner: string,
  repo: string,
  pull_number: number,
  prTitle: string,
  adrContent: string
) {
  const date = new Date().toISOString().split("T")[0];
  const slug = prTitle.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 50);
  const path = `docs/decisions/${date}-${slug}-pr${pull_number}.md`;

  try {
    let sha: string | undefined;
    try {
      const existing = await octokit.repos.getContent({ owner, repo, path });
      sha = (existing.data as any).sha;
    } catch {
      // File doesn't exist yet — that's fine
    }

    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path,
      message: `docs: add ADR for PR #${pull_number} [skip ci]`,
      content: Buffer.from(adrContent).toString("base64"),
      ...(sha ? { sha } : {}),
    });

    console.log(`[DevDox] ADR saved to ${path}`);
    return path;
  } catch (err: any) {
    console.warn(`[DevDox] Could not save ADR to repo: ${err.message}`);
    return null;
  }
}

export async function handlePROpened({ payload }: { payload: any }) {
  const pr = payload.pull_request;
  const owner = payload.repository.owner.login;
  const repo = payload.repository.name;
  const pull_number = pr.number;
  const prUrl = pr.html_url;
  const prTitle = pr.title;
  const prBody = pr.body || "";
  const changedFiles = pr.changed_files ?? 0;
  const installationId = payload.installation?.id;

  console.log(`[DevDox] PR #${pull_number} opened in ${owner}/${repo}`);

  if (!installationId) {
    console.error("[DevDox] No installation ID in payload");
    return;
  }

  // ── IDEMPOTENCY CHECK ──────────────────────────────────────────
  const idempotencyKey = `processed:${owner}/${repo}:${pull_number}`;
  const alreadyProcessed = await getCache(idempotencyKey);
  if (alreadyProcessed) {
    console.log(`[DevDox] Skipping duplicate webhook for PR #${pull_number}`);
    return;
  }
  await setCache(idempotencyKey, "true");

  // ── AUTH ───────────────────────────────────────────────────────
  let octokit: Octokit, token: string;
  try {
    const auth = await getInstallationAuth(installationId);
    octokit = auth.octokit;
    token = auth.token;
  } catch (err: any) {
    console.error("[DevDox] Auth failed:", err.message);
    return;
  }

  // ── SKIP-DOCS OPT-OUT ──────────────────────────────────────────
  if (prBody.includes("[skip-docs]") || prBody.includes("[no-adr]")) {
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: pull_number,
      body: `📝 **DevDox** skipped this PR — \`[skip-docs]\` found in description.`,
    });
    console.log(`[DevDox] Skipped PR #${pull_number} — skip-docs flag`);
    return;
  }

  // ── SMART PR DETECTION ─────────────────────────────────────────
  const shouldSkip = SKIP_PATTERNS.some(p => p.test(prTitle));
  if (shouldSkip || changedFiles < 2) {
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: pull_number,
      body: `🔇 **DevDox** skipped: this looks like a minor change.\n\nAdd meaningful commits or remove \`wip/draft\` from the title for a full ADR.`,
    });
    console.log(`[DevDox] Skipped PR #${pull_number} — minor change`);
    return;
  }

  // ── ENSURE DOCS FOLDER EXISTS ──────────────────────────────────
  await ensureDocsFolder(octokit, owner, repo);

  // ── THINKING COMMENT ───────────────────────────────────────────
  const thinkingComment = await octokit.issues.createComment({
    owner,
    repo,
    issue_number: pull_number,
    body: `## 🤖 DevDox is analyzing this PR...\n\n> Fetching commits, linked tickets, and discussions. ADR will appear here in ~15 seconds.`,
  });

  // ── ANALYZE & POST ─────────────────────────────────────────────
  try {
    const result = await analyzePR(prUrl, token) as AnalysisResult;
    const commentBody = formatADRComment(result, prUrl);

    const [, adrPath] = await Promise.all([
      octokit.issues.updateComment({
        owner,
        repo,
        comment_id: thinkingComment.data.id,
        body: commentBody,
      }),
      saveADRToRepo(octokit, owner, repo, pull_number, prTitle, result.suggestedADR),
    ]);

    console.log(`[DevDox] ADR posted and saved for PR #${pull_number}`);
  } catch (err: any) {
    console.error(`[DevDox] Analysis failed for PR #${pull_number}:`, err.message);

    await octokit.issues.updateComment({
      owner,
      repo,
      comment_id: thinkingComment.data.id,
      body: `## 🤖 DevDox — Analysis Failed\n\n> ❌ ${err.message}\n\nPlease check your configuration or try again.`,
    });
  }
}